# Generated by Django 5.1.7 on 2025-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_skillproficiency"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="badge_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
